### ISSUE TITLE
vm.exec() with multiline is broken?!?

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#104]
I'm work on a updated selenium unitests... But it seems that multiline code will not work anymore.

e.g.:
```
vm.exec('print "one"\nprint "two"');
```
will result in:
```
debug: OperationError:
debug:  operror-type: SyntaxError
debug:  operror-value: ('EOL while scanning string literal', ('c callback', 1, 6, 'exec \'print "one"\n', 0))
>>>
```
next try:
```
vm.exec('print "one"\\nprint "two"');
```
result:
```
debug: OperationError:
debug:  operror-type: SyntaxError
debug:  operror-value: ('Unknown character', ('<string>', 1, 12, 'print "one"\\nprint "two"\n', 0))
>>> 
```

This has been worked yesterday, isn't it?

**Comment by jedie** [comment]
Should i use ```vm._execute_source()``` ???

**Comment by rfk** [comment]
Whoops, looks like I broke then when I split up the functionality into `exec` and `exec`.  Working on a fix now...

**Comment by rfk** [comment]
Fixed by https://github.com/rfk/pypyjs/commit/c16548e95e03a755a3931f44be5fb343b228e513 in some simple tests; let me know if you run into any more cases where it's broken.

**Comment by rfk** [comment]
> Should i use vm._execute_source()

BTW the short answer to this is "no"; that one's only really for intenal use since it runs in the raw global scope rather than a carefully managed namespace for user code.

**Comment by jedie** [comment]
Yes https://github.com/rfk/pypyjs/commit/c16548e95e03a755a3931f44be5fb343b228e513 fixed the problem. So i switched back to vm.exec() with https://github.com/jedie/pypyjs/commit/7f12592f42fd209a4b54cd19c808271f07053b23

Btw. should i explicit test if ```vm._execute_source("print __name__")``` will return ```__main__```, too?

**Comment by rfk** [comment]
> should i explicit test if vm._execute_source("print __name__") will return __main__, too?

No, that's not part of the public API so I don't want to commit to any particulars of how it should behave.

**Comment by jedie** [comment]
With https://github.com/jedie/pypyjs/commit/ff6e61d8ac66be3edfd87ec701d72594aa89ac0e i use  ```vm.exec()``` in editor page, too.

But now i didn't get any error messages in console. Any idea?

**Comment by rfk** [comment]
Ah, so as of https://github.com/rfk/pypyjs/commit/7fddfb02c011e2a9bd824bf2cd28d0255d33ce25 I made `exec` propagate the error up to javascript, like this:
```
  vm.exec("raise ValueError(42)").catch(function(err) {
    // err is an instance of PyPyJS.Error
    console.log(err.name)  // "ValueError"
    console.log(err.message) // "42"
    console.log(err.trace)  // the human-readable traceback, as a string
  })
```

I think this is more flexible for the calling code.  You could do something like this to get the old behaviour back:

```
  vm.eval(code).catch(function(err) { vm.stderr(err.trace); })
```

**Comment by jedie** [comment]
Thanks for the information!

The current solution since https://github.com/jedie/pypyjs/commit/a5408122dd3418cb7f15c8b672a7252eb96400df :

```
            var start_time = new Date();
            vm.exec(code).then(function() {
                var duration = new Date() - start_time;
                $("#run_info").text("Run in " + duration + "ms (OK)");
            }, function (err) {
                // err is an instance of PyPyJS.Error
                var duration = new Date() - start_time;
                $("#run_info").text("Run in " + duration + "ms ("+err.name+": "+err.message+"!)");
                vm.stderr(err.trace); // the human-readable traceback, as a string
            });
```

I didn't find a way to use ```.catch``` here. I need **is run is OK** and **if failed**

**Comment by crantila** [comment]
While I don't really understand the reasons behind the change mentioned [here](https://github.com/pypyjs/pypyjs/issues/104#issuecomment-102990433), I was wondering if we could write it in the README documentation? This inconsistency was thoroughly unexpected for me, and the fact that the error propagation in JavaScript tends to be delayed arbitrarily makes this seem like it isn't intentional. The workaround isn't very difficult, but it might never occur to you if you aren't expecting it.

I've also made a [gist](https://gist.github.com/crantila/69a4b6689beee5ebab1a) to help avoid future programmers from spending hours trying to get ``stderr`` to work.

Thanks!

**Comment by bioball** [comment]
Hey all,

Is this problem fixed? I've just started working with pypyjs this week, and am seeing this error pop up. It seems like it's working fine on pypyjs.github.io, but I have no clue how it's working there.

If I open my browser console on http://pypyjs.org/editor.html and input `vm.eval(CodeMirrorEditor.getValue())`, I see the EOL error. However, if I click the "run" button, it works fine. What's going on here?

On my own project, I'm working with the latest version of pypyjs/pypyjs-release.

**Comment by kirbyfan64** [comment]
I think pypyjs.github.io uses the development version, not the release (though I'm not sure).

**Comment by crantila** [comment]
I'm not entirely sure what issue @bioball has&mdash;is there a possibility that you're confusing ``eval()`` and ``exec()``? The ``pypyjs.eval()`` function is only intended for the same situations as the corresponding Python builtin function ([specified here](https://docs.python.org/2.7/library/functions.html#eval)).

The default contents of the text editor on ``editor.html`` aren't valid for Python's built-in ``eval()``, so if that's what you're running from the browser console, it shouldn't work. On the other hand, the "run" button probably uses ``pypyjs.exec()`` so that the code does work.

Does this help? Or are you having a different issue?

**Comment by bioball** [comment]
OH. Gotcha. I didn't know about `exec`. Thanks for the help.
