### ISSUE TITLE
strange Traceback ?!?

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#127]
I found a strange traceback change...

e.g.:
This code:
```
import Queue
```
results in:
```
Traceback (most recent call last):
  File "c callback", line 22, in <module>
  File "<string>", line 1, in <module>
  File "/lib/pypyjs/lib_pypy/Queue.py", line 7, in <module>
    import dummy_threading as _threading
  File "/lib/pypyjs/lib_pypy/dummy_threading.py", line 45, in <module>
    import threading
ImportError: No module named threading
```

That's normal.

Just try to use ```__import__()``` with a string:
```
import traceback

try:
    __import__("Queue")
except ImportError as err:
    print "ERROR: %s" % err
    traceback.print_exc()
```
result in:
```
ERROR: No module named Queue
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: No module named Queue
```
That's not the complete traceback, isn't it?

and now the strange one:
```
import traceback

"import Queue"

try:
    __import__("Queue")
except ImportError as err:
    print "ERROR: %s" % err
    traceback.print_exc()
```
results in:
```
ERROR: No module named threading
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/lib/pypyjs/lib_pypy/Queue.py", line 7, in <module>
    import dummy_threading as _threading
  File "/lib/pypyjs/lib_pypy/dummy_threading.py", line 45, in <module>
    import threading
ImportError: No module named threading
```

I get the full traceback, because of the existing DocString **"import Queue"** ?!?
I can change **"import Queue"** to **# import Queue** and move it to the end, with the same result.

**Comment by jedie** [comment]
Ah! It's because of ```PyPyJS.prototype.findImportedNames``...
This scans the code for "import foo" everywhere, before execution.

Using ast module, will not help here, isn't it?

**Comment by kirbyfan64** [comment]
IMO, scanning for modules ahead of time should use a real parser; this evidently would cause trouble if the word "import" shows up in a string.

**Comment by jedie** [comment]
If the ast module used here (see also: https://github.com/rfk/pypyjs/issues/109#issuecomment-103825389 ) then it will not poke module names from strings...

But the traceback, will be stay as the shortest one, isn't it?

**Comment by perkinslr** [comment]
Also, some way of detecting conditional imports would be nice.  I've got a script that checks `if sys.platform=='js'` and only imports certain things since functionality is obviously reduced.  Problem is it still has to wait for the modules that won't actually get imported to be copied into the cache.  I ended up using importlib.import_library to sidestep the findImportedNames hook.

**Comment by perkinslr** [comment]
Oh, and if you want Queue, I've got dummy_threading importable, and Queue will happily fall back to dummy_threading, it's in my fork.  Or you can modify Queue.py to skip the lock checks, since there will never be a failure to lock.acquire().

**Comment by jedie** [comment]
> Oh, and if you want Queue...

No, it's only a example

**Comment by rfk** [comment]
> scanning for modules ahead of time should use a real parser;
>  this evidently would cause trouble if the word "import" shows up in a string.

Yes it should, the current regexp-based version was just to get something up and running quickly.

Note that the cost of a false positive match is very small though, at worst it can cause us to pull in the .py files for a module that's not actually required.  If doing a proper parse turns out to be slower, it may not be worth making the switch. 

> But the traceback, will be stay as the shortest one, isn't it?

Right.

This whole `findImportedNames` thing is a really gross hack.  It's only here because we can't do a synchronous XHR to fetch files in the browser, so we can't populate the interpreter's virtual filesystem on-demand - you either have to pull in everything you need up-front, or carefully pull in the files you need before calling into the interpreter.

I'd really like it to go away at some point, but that will depend on getting the interpreter code suspendible in some manner, like in #76, #37, #9.  Then we could implement an async fileystem API that pulls directly from the server on-demand.

**Comment by rfk** [comment]
(closing this out because I don't think there's anything actionable here, but hopefully we can make this better over time)
