### ISSUE TITLE
standalone html package?

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#25]
I tried the DEMO page: http://pypyjs.org/demo/

Very cool!

I see, that the needed "pypy.vm.js" will be requested by JS via XMLHttpRequest()... So i can't just svae all files locally and play with them.

Why using XMLHttpRequest? Why not include it in html file as a normal, static js file?

It would be great to have a self contained, standalone package to start playing with pypyjs!

**Comment by rfk** [comment]
Sorry to leave this sitting idle for so long :-(

>This repro contains only the compiled stuff... Think this makes sense, because the main repo is very, very big... ;)

Indeed.  I'm going to start publishing release bundles with just the compiled code, which should make this easier for folks who just want to use it rather than build it.

>  the needed "pypy.vm.js" will be requested by JS via XMLHttpRequest()... So i can't just svae all files locally and play with them.

One option here would be to detect `file://` urls and use a different API for loading them.  We've had several people hit this problem with having to run a local server for development.  See #48.

Will the combination of release bundles and local-file support satisfy your needs here?  I'm going to close this out in favour of the above bug, but please feel free to re-open or file follow-up bugs if there's more we can do to support the use-case.
