### ISSUE TITLE
LookupError: unknown encoding: string-escape

### ISSUE THREAD

**Issue by mattjmorrison** [rfk/pypyjs#83]
This error happens when doing the following:

```
>>> import pickle
>>> pickle.loads(pickle.dumps({'a': 'a'}))
```

**Comment by rfk** [comment]
Thanks for the report!  Encoding handling is currently a little weird, we pre-load encoding modules at initialization time to make sure they're visible to python's magic encoding finder.  Turns out `string-escape` wasn't in the list.  I added it in https://github.com/rfk/pypyjs/commit/7aa0ecad4aea598d39460ec89025a5acaf942cff so this should be fixed in the next release.

**Comment by jedie** [comment]
in current version:
```
>>> import pickle
>>> pickle.loads(pickle.dumps({'a': 'a'}))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/pypyjs/lib_pypy/pickle.py", line 1425, in loads
    return Unpickler(file).load()
  File "/lib/pypyjs/lib_pypy/pickle.py", line 901, in load
    dispatch[key](self)
  File "/lib/pypyjs/lib_pypy/pickle.py", line 1014, in load_string
    self.append(rep.decode("string-escape"))
LookupError: unknown encoding: string-escape
>>> 
```

**Comment by rfk** [comment]
> Is the current builded version not up to date

I just pushed an updated build into the `website` directory; hopefully will get to tagging a 0.3.0 with all these fixes sometime this weekend.

> ?!?

FWIW, I can't tell whether this is expressing enthusiasm, frustation, or some mix of both... :-)
